### ISSUE TITLE
AWSCognitoIdentityProvider

### ISSUE THREAD

**Issue by cagatayozgur** [awslabs/aws-sdk-xamarin#10]
The post located here: http://mobile.awsblog.com/post/Tx2FL1QAPDE0UAH/Understanding-Amazon-Cognito-Authentication-Part-2-Developer-Authenticated-Ident

mentions the following:
The AWS Mobile SDK has been updated to support this flow via the use of a new interface called AWSCognitoIdentityProvider. See the Developer Guides (iOS|Android) for information on implementing these providers.

Is this already available? If not, is it planned in the upcoming iterations?

Thanks in advance

Chad

**Comment by cagatayozgur** [comment]
Hi Tara,

Did you have a chance to look into this?

Best

c

**Comment by tawalke** [comment]
Yes I did.  I’m working on a new release to correct some of the issues.  My goal is to be complete by next week or sooner. 






Sent from Windows Mail





From: Chad Ozgur
Sent: ‎Thursday‎, ‎January‎ ‎15‎, ‎2015 ‎8‎:‎22‎ ‎PM
To: 'awslabs/aws-sdk-xamarin'
Cc: Tara Walker





Hi Tara,

Did you have a chance to look into this?

Best

c

**Comment by cagatayozgur** [comment]
Awesome, can't wait for the next release.

Thanks!

C

**Comment by cagatayozgur** [comment]
Hi Tara,

Any update on this project?

Best

c

**Comment by tawalke** [comment]
Hi Chad, this was updated at the end of January.  Were you able to try the new release?

Sent from my Windows Phone
________________________________

**Comment by cagatayozgur** [comment]
Yeah, I realized after I posted the message.
The nuget version did not work for me, also the source refused to compile
due to various reasons. So I went ahead with the compiled binaries. I will
test today and report back.
First thing I realized, using the unifiedAPI dll, dynamoDB
context.createBatchWrite causes the UI to hang and app to crash in 10-15
seconds.
Creating and amazons3Client with credentials from federatated login, causes
a "parameter cannot be null. Stream" error.
I wasn't able to observe any of the above with the classic API version.

Best

c


On Tue, Feb 24, 2015 at 3:23 AM, tawalke <notifications@github.com> wrote:

> Hi Chad, this was updated at the end of January. Were you able to try the
> new release?
>
> Sent from my Windows Phone
> ________________________________
> From: Chad Ozgur<mailto:notifications@github.com>
> Sent: ‎2/‎23/‎2015 10:02 PM
> To: awslabs/aws-sdk-xamarin<mailto:aws-sdk-xamarin@noreply.github.com>
> Cc: tawalke<mailto:taraew@live.com>
> Subject: Re: [aws-sdk-xamarin] AWSCognitoIdentityProvider (#10)
>
> Hi Tara,
>
> Any update on this project?
>
> Best
>
> c
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/awslabs/aws-sdk-xamarin/issues/10#issuecomment-75690147
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awslabs/aws-sdk-xamarin/issues/10#issuecomment-75716336>
> .
>



-- 
Thanks And Regards

Chad Ozgur


Creative Technology
www.wildcardnewyork.com
cagatay@wildcardnewyork.com

115 East 23rd Street
10010 New York NY

+1 888 729 0464

**Comment by tawalke** [comment]
Thanks Chad.  I have been testing the Unified API dll, and it is behaving differently on different machines.  I am working on the next release so I will make a decision by the end of next week on whether to re-architect the Unified for the next release or if current release just needs tweaks. 


-Tara






Sent from Windows Mail





From: Chad Ozgur
Sent: ‎Tuesday‎, ‎February‎ ‎24‎, ‎2015 ‎8‎:‎39‎ ‎AM
To: 'awslabs/aws-sdk-xamarin'
Cc: Tara Walker




Yeah, I realized after I posted the message.
The nuget version did not work for me, also the source refused to compile
due to various reasons. So I went ahead with the compiled binaries. I will
test today and report back.
First thing I realized, using the unifiedAPI dll, dynamoDB
context.createBatchWrite causes the UI to hang and app to crash in 10-15
seconds.
Creating and amazons3Client with credentials from federatated login, causes
a "parameter cannot be null. Stream" error.
I wasn't able to observe any of the above with the classic API version.

Best

c


On Tue, Feb 24, 2015 at 3:23 AM, tawalke <notifications@github.com> wrote:

> Hi Chad, this was updated at the end of January. Were you able to try the
> new release?
>
> Sent from my Windows Phone
> ________________________________
> From: Chad Ozgur<mailto:notifications@github.com>
> Sent: ‎2/‎23/‎2015 10:02 PM
> To: awslabs/aws-sdk-xamarin<mailto:aws-sdk-xamarin@noreply.github.com>
> Cc: tawalke<mailto:taraew@live.com>
> Subject: Re: [aws-sdk-xamarin] AWSCognitoIdentityProvider (#10)
>
> Hi Tara,
>
> Any update on this project?
>
> Best
>
> c
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/awslabs/aws-sdk-xamarin/issues/10#issuecomment-75690147
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awslabs/aws-sdk-xamarin/issues/10#issuecomment-75716336>
> .
>



-- 
Thanks And Regards

Chad Ozgur


Creative Technology
www.wildcardnewyork.com
cagatay@wildcardnewyork.com

115 East 23rd Street
10010 New York NY

+1 888 729 0464

**Comment by tawalke** [comment]
@cagatayozgur : If you compile the Unified project from source (latest), you should have no more problems.  The NuGet package is loading the iOS Classic assembly, and a new package will be created and updated so that this does not occur.  To compile ensure that you have the compilation directives from the debug view of solution in the release version prior to compile.
